### ISSUE TITLE
Data download issue with the script

### ISSUE THREAD

**Issue by miranghimire-fm** [ai-forever/StackMix-OCR#24]
Hi, currently upon downloading the dataset using the following code doesn't seem to working. Same seems to be the issue for other dataset as well:
`python scripts/download_dataset.py --dataset_name 'iam' `
Are we expected to prepare the dataset and marking.csv ourselves?

**Comment by skalinin** [comment]
yes, for now it'd better to prepare marknig.csv by yourself

The repo requires in refactoring
